# SELECT ROUND(AVG(DAILY_FEE),0)
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV'

-- 코드를 입력하세요
SELECT  ROUND(AVG(DAILY_FEE),0) AVERAGE_FEE 
FROM    CAR_RENTAL_COMPANY_CAR A
WHERE   1=1
        AND CAR_TYPE = 'SUV'