-- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, PRICE * SALES_AMOUNT AS SALES
SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT) * PRICE AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE USING(PRODUCT_ID)
GROUP BY PRODUCT_ID
ORDER BY 2 DESC, 1

# SELECT p.PRODUCT_CODE , sum(p.PRICE * o.SALES_AMOUNT) as SALES
# from PRODUCT as p join OFFLINE_SALE as o
# on p.PRODUCT_ID = o.PRODUCT_ID
# group by p.PRODUCT_ID
# order by 2 desc ,1
