SELECT 
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM 
    ONLINE_SALE 
WHERE 
    MONTH(SALES_DATE)=3 
UNION ALL
SELECT 
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),
    PRODUCT_ID,
    NULL,
    SALES_AMOUNT
FROM 
    OFFLINE_SALE 
WHERE 
    MONTH(SALES_DATE)=3 
ORDER BY 
    1,2,3

# SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE MONTH(SALES_DATE)=3
# UNION 
# SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE MONTH(SALES_DATE)=3
# ORDER BY PRODUCT_ID ASC, PRODUCT_ID ASC, USER_ID ASC


# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# UNION

# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;