# SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
# FROM FISH_INFO FI LEFT JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
# GROUP BY FI.FISH_TYPE, FNI.FISH_NAME;

SELECT  COUNT(FI.ID) AS FISH_COUNT
        ,FN.FISH_NAME
  FROM  FISH_INFO AS FI
  JOIN  FISH_NAME_INFO AS FN
    ON  FI.FISH_TYPE = FN.FISH_TYPE
 GROUP
    BY  FISH_NAME
 ORDER
    BY  FISH_COUNT DESC