-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO USING(PRODUCT_ID)
WHERE DATE_FORMAT(FO.PRODUCE_DATE, "%Y-%m") = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, PRODUCT_ID