WITH RECURSIVE RC AS(
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM RC
    WHERE HOUR < 23
)


SELECT
    HOUR,
    COALESCE(CNT, 0) AS COUNT
FROM
    RC
LEFT OUTER JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS O USING(HOUR)
ORDER BY
    RC.HOUR