SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, COUNT(MEMBER_ID) OVER(PARTITION BY MEMBER_ID) AS COUNT_REVIEW
    FROM REST_REVIEW
) AS R
JOIN MEMBER_PROFILE AS P
ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.COUNT_REVIEW = (
    SELECT MAX(COUNT_REVIEW)
    FROM (
        SELECT COUNT(MEMBER_ID) OVER(PARTITION BY MEMBER_ID) AS COUNT_REVIEW
        FROM REST_REVIEW
    ) AS SUB
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;
