WITH CTE AS (
    SELECT
        MEMBER_ID,
        COUNT(*) AS M
    FROM
        MEMBER_PROFILE AS MP
    JOIN REST_REVIEW AS RR USING(MEMBER_ID)
    GROUP BY
        MEMBER_ID
)

SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM
    REST_REVIEW AS RR
JOIN MEMBER_PROFILE AS MP USING(MEMBER_ID)
WHERE MEMBER_ID IN  (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*)= (
        SELECT MAX(M)
        FROM CTE)
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;