SELECT DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_DEPARTMENT
JOIN HR_EMPLOYEES USING(DEPT_ID)
GROUP BY DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC

# SELECT DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL)) AS AVG_SAL
# FROM HR_DEPARTMENT
# JOIN HR_EMPLOYEES USING(DEPT_ID)
# GROUP BY DEPT_ID, DEPT_NAME_EN
# ORDER BY AVG_SAL DESC;